In [6]:
import numpy as np

my_list = [1,2,44,5]
type(np.array(my_list))
arr = np.array(my_list) #This is conver a list to numpy array
arr


array([ 1,  2, 44,  5])

In [6]:
np.arange(0,11) #This is work for range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.random.randint(0,10) #this is genarate Random Number form your range 

3

In [20]:
np.random.randint(0,1000,(5,7)) #This is genarate Random Number form your range and divide it into given row and colum
#here 1st number 5 indigate row and 2nd number 7 indigate colum (****)

array([[754, 239, 333, 693, 970, 995, 225],
       [893, 385, 932,   8,  10, 152, 222],
       [999, 225, 125, 185, 241, 854, 570],
       [457, 833, 200, 496, 239, 235, 748],
       [224, 972, 185, 665, 973, 913, 984]])

In [34]:
np.random.seed(101) #This is for contant a random list
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [39]:
arr.max() #This is for max item
arr.min()  #This is for min item
arr.mean() #This is for Avarage all of item
arr.argmax() #This is for max item index number
arr.argmin() #This is for min item index number
arr.reshape(2,5) #This is for divide colum and row of the list (2=row,5=colum)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [42]:
mat = np.arange(0,100).reshape(10,10) # here we reshape and create a array with 1-99 num
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [48]:
mat[2,3] # here (2=row, 3=colum)
mat[0,:] #this is for Full row's number
mat[:,0] #this is for full colum's number
mat[0:3,0:3] # This is for Slicing the row and colum

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [5]:
l3 = [True,'2',2,3.0]
l4 = [type(i) for i in l3]
l4

[bool, str, int, float]

In [37]:

l = np.arange(1,10)
a = np.array([1.4,2.0,3],dtype='int')
a

array([1, 2, 3])

In [44]:
 np.array([range(i, i + 3) for i in [1,4,7]])
# Create an array filled with a linear sequence
 # Starting at 0, ending at 20, stepping by 2
 # (this is similar to the built-in range() function)
np.linspace(0,1,5)
np.arange(0, 1, .05)


array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [20]:
np.random.seed(0) # seed for reproducibility/Unchangeable
x1 = np.random.randint(10, size=6)# One-dimensional array
x2 = np.random.randint(0,100,(3,4,5)) #Three Dimentional array
x3 = np.random.randint(0,10,(3,3))
x3

array([[8, 1, 1],
       [7, 9, 9],
       [3, 6, 7]])

In [19]:

x3[2,0] #First number goes to down thats mean colum 2nd indext goes to in row
x3[2,-1] # here -1 goes to last index in the array


7

In [23]:
np.mod(3,2)

1

array([[0.17090959, 0.35815217, 0.75068614],
       [0.60783067, 0.32504723, 0.03842543],
       [0.63427406, 0.95894927, 0.65279032],
       [0.63505887, 0.99529957, 0.58185033],
       [0.41436859, 0.4746975 , 0.6235101 ],
       [0.33800761, 0.67475232, 0.31720174],
       [0.77834548, 0.94957105, 0.66252687],
       [0.01357164, 0.6228461 , 0.67365963],
       [0.971945  , 0.87819347, 0.50962438],
       [0.05571469, 0.45115921, 0.01998767]])